name: GitHub Actions
run-name: ${{ github.actor }} is testing out ${{ github.repository }}

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.0'

      - name: Check out ImGui repository
        uses: actions/checkout@v4
        with:
          repository: ocornut/imgui
          show-progress: false
          path: imgui

      - name: Check out CMakeForImGui
        uses: actions/checkout@v4
        with:
          repository: adembudak/CMakeForImGui
          show-progress: false
          path: CMakeForImGui

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}/CMakeForImGui
          triplet: x64-windows
          token: ${{ github.token }}

      - name: Configure ImGui with CMakeForImGui
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui
          -B ${{ github.workspace }}/build
          -G "Visual Studio 17 2022"
          -D VCPKG_MANIFEST_MODE=ON
          -D VCPKG_MANIFEST_DIR=${{ github.workspace }}/CMakeForImGui
          -D CMAKE_INSTALL_PREFIX=${{ github.workspace }}/install.in.here
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D install=ON
          -D install_examples=OFF
          -D examples=OFF
          -D uninstall=OFF
          -D DearImGui_Misc_Options=ON -D DearImGui_Misc_Cpp=ON -D DearImGui_Misc_FreeType=ON -D DearImGui_Misc_Debugger=ON -D DearImGui_Misc_Fonts=ON
          -D pkg-config=ON
          -D DearImGui_Backend_Allegro5=ON
          -D DearImGui_Backend_FreeGLUT=ON
          -D DearImGui_Backend_GLFW=ON
          -D DearImGui_Backend_OpenGL2=ON
          -D DearImGui_Backend_OpenGL3=ON
          -D DearImGui_Backend_Vulkan=ON
          -D DearImGui_Backend_SDL2=ON
          -D DearImGui_Backend_SDLRenderer2=ON
          -D DearImGui_Backend_SDL3=ON
          -D DearImGui_Backend_SDLGPU3=ON
          -D DearImGui_Backend_SDLRenderer3=ON
          -D DearImGui_Backend_WebGPU=OFF
          -D DearImGui_Backend_Win32=ON
          -D DearImGui_Backend_DirectX9=ON
          -D DearImGui_Backend_DirectX10=ON
          -D DearImGui_Backend_DirectX11=ON
          -D DearImGui_Backend_DirectX12=ON
          --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build ImGui
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config Release

      - name: Fix install paths
        run: >
          (Get-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake")
          | ForEach-Object {$_ -replace 'D:\\a\\CMakeForImGui.test\\', 'D:/a/CMakeForImGui.test/'}
          | Set-Content -Path "${{ github.workspace }}\\build\\cmake_install.cmake"

      - name: Install ImGui
        run: >
          cmake
          --install ${{ github.workspace }}/build
          --config Release

      - name: Check out CMakeForImGui.test
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: CMakeForImGui.test

      - name: Configure examples
        run: >
          cmake
          -S ${{ github.workspace }}/CMakeForImGui.test
          -B ${{ github.workspace }}/build-examples
          -D IMGUI_SOURCE_DIR=${{ github.workspace }}/imgui
          -D DearImGui_DIR=${{ github.workspace }}/install.in.here/lib/cmake/DearImGui
          -G "Visual Studio 17 2022"
          -D VCPKG_MANIFEST_MODE=ON
          -D VCPKG_MANIFEST_DIR=${{ github.workspace }}/CMakeForImGui.test/.github/workflows
          --toolchain ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build examples
        run: >
          cmake
          --build ${{ github.workspace }}/build-examples
          --config Release

      - run: echo "Job exited by ${{ job.status }}."
